In [ ]:
import pandas as pd

In [3]:
df1 = pd.read_csv('store_1_sales.csv')
df2 = pd.read_csv('store_2_sales.csv')
df3 = pd.read_csv('store_3_sales.csv')
df = pd.concat([df1, df2, df3])
df

,Date,Item Code,Category,Quantity Sold,Price,Total Sale
0,2023-09-01 10:32:00,101.0,Электроника,2.0,30000.0,60000.0
1,2023-09-01 11:45:00,202.0,Одежда,1.0,5000.0,5000.0
2,2023-09-02 14:20:00,101.0,Электроника,1.0,30000.0,30000.0
3,2023-09-03 13:00:00,303.0,Продукты,10.0,200.0,2000.0
4,2023-09-03 16:50:00,404.0,Бытовая техника,1.0,15000.0,15000.0
5,2023-09-04 12:15:00,202.0,Одежда,3.0,5000.0,15000.0
6,2023-09-04 15:30:00,404.0,Бытовая техника,1.0,15000.0,15000.0
7,2023-09-05 09:00:00,303.0,Продукты,5.0,200.0,1000.0
8,2023-09-06 17:30:00,505.0,Канцелярия,15.0,100.0,1500.0
9,2023-09-06 11:45:00,202.0,Одежда,NaN,5000.0,NaN
10,2023-09-07 12:45:00,101.0,Электроника,2.0,NaN,NaN
11,2023-09-08 14:20:00,303.0,NaN,10.0,200.0,2000.0
12,2023-09-08 16:00:00,NaN,NaN,5.0,5000.0,25000.0
0,2023-09-01 12:10:00,101.0,Электроника,1.0,30000.0,30000.0
1,2023-09-01 13:45:00,202.0,Одежда,2.0,5000.0,10000.0
2,2023-09-02 11:00:00,404.0,Бытовая техника,1.0,15000.0,15000.0
3,2023-09-03 12:50:00,303.0,Продукты,5.0,200.0,1000.0
4,2023-09-03 17:30:00,505.0,Канцелярия,10.0,100.0,1000.0
5,2023-09-04 09:15:00,303.0,Продукты,20.0,200.0,4000.0
6,2023-09-04 13:50:00,101.0,Электроника,1.0,30000.0,30000.0
7,2023-09-05 14:35:00,202.0,Одежда,4.0,5000.0,20000.0
8,2023-09-06 18:20:00,404.0,Бытовая техника,1.0,15000.0,15000.0
9,2023-09-06 10:00:00,505.0,Канцелярия,20.0,NaN,NaN
10,2023-09-07 11:00:00,303.0,Продукты,15.0,200.0,3000.0
11,2023-09-07 14:10:00,404.0,Бытовая техника,1.0,NaN,15000.0
12,2023-09-08 13:00:00,NaN,NaN,10.0,1000.0,10000.0
0,2023-09-01 09:20:00,202.0,Одежда,1.0,5000.0,5000.0
1,2023-09-02 14:15:00,505.0,Канцелярия,20.0,100.0,2000.0
2,2023-09-03 15:50:00,404.0,Бытовая техника,1.0,15000.0,15000.0
3,2023-09-04 10:00:00,101.0,Электроника,2.0,30000.0,60000.0
4,2023-09-04 11:40:00,303.0,Продукты,15.0,200.0,3000.0
5,2023-09-05 10:30:00,202.0,Одежда,2.0,5000.0,10000.0
6,2023-09-06 13:15:00,404.0,Бытовая техника,1.0,15000.0,15000.0
7,2023-09-06 17:45:00,303.0,Продукты,10.0,200.0,2000.0
8,2023-09-07 09:00:00,505.0,Канцелярия,30.0,100.0,3000.0
9,2023-09-07 14:20:00,101.0,Электроника,NaN,30000.0,NaN
10,2023-09-08 11:00:00,NaN,NaN,5.0,200.0,1000.0
11,2023-09-08 15:10:00,202.0,Одежда,4.0,5000.0,20000.0
12,2023-09-08 16:45:00,505.0,Канцелярия,15.0,NaN,NaN

In [9]:
pd.pivot_table(data=df, values=['Quantity Sold', 'Total Sale'], index=['Category'],
               aggfunc={'Quantity Sold': 'sum', 'Total Sale': ['sum', 'mean']}).to_csv('data.txt', sep='\t')